name: GitHub Actions Node Demo
on:
  push:
    branches: main #[ $default-branch ]
  pull_request:
    branches: main

jobs:

  buildApp:
    uses: adelanre/shared-pipeline/.github/workflows/node.js.yml@main
    with:
      node-version: 12.x

  docker:
    needs: [buildApp]
    uses: adelanre/shared-pipeline/.github/workflows/docker.yml@main
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Just a dummy step"

  containerScan:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - run: echo "This will scan container"
    #uses: adelanre/shared-pipeline/.github/workflows/container-scan.yml@main

  deploy-sandbox:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - run: echo "This will deploy the workload" #PAT: glpat-yScB5vrg8Cat5bSztfxJ
  
  deploy-qa:
    runs-on: ubuntu-latest
    needs: [deploy-sandbox,containerScan]
    steps:
    - run: echo "This will deploy the workload"
  
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [deploy-qa]
    steps:
    - run: echo "This will deploy the workload"

  run-automated-test:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
    - run: echo "This will deploy the workload"
  
  run-integration-test:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
    - run: echo "This will deploy the workload"
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [run-automated-test,run-integration-test]
    steps:
    - run: echo "This will deploy the workload"
